<div class="porto-grid-container">
    <div id="banner-masonry-demo-7" class="porto-banner-layout mb-4 pb-2 porto-preset-layout" style="opacity: 1; position: relative; height: 528px;">
        <div class="porto-grid-item grid-col-1-2 grid-col-md-1 grid-height-1" style="position: absolute; left: 0%; top: 0px;">
            <div class="porto-ibanner" style="background: #3d4b58;">
                <img src="https://www.portotheme.com/magento2/porto/pub/media/wysiwyg/smartwave/porto/homepage/07/shop7_home_banner1.jpg">
                <div class="porto-ibanner-desc no-padding d-flex">
                    <div class="porto-ibanner-layer" style="left: 7%; bottom: 8%;">
                        <h5 style="font-size: 0.875em; color: rgba(255, 255, 255, 0.7); line-height: 1.4; font-weight: 500; letter-spacing: 0.08em;" class="vc_custom_heading mb-2 align-left">Find the Boundaries</h5>
                        <h3 style="font-size: 2.5em; line-height: 1; letter-spacing: 0.1px;" class="vc_custom_heading custom-font4 mb-1 align-left heading-light">Flash Sale</h3>
                        <h4 style="font-size: 4.75em; line-height: 1;" class="vc_custom_heading mb-2 align-left text-uppercase heading-light">70% OFF</h4>
                        <h5 style="font-size: 0.6875em; line-height: 1; letter-spacing: -0.02em;margin-right: 1.2em;" class="vc_custom_heading pull-left p-t-sm align-left heading-light">STARTING AT</h5>
                        <h5 style="font-size: 0.9375em; line-height: 1;" class="vc_custom_heading coupon-sale-text align-left">
                            <b><sup>$</sup>199<sup>99</sup></b>
                        </h5>
                        <div class="btn-container mt-2 mb-0 d-inline-block">
                            <a class="btn btn-modern btn-lg btn-light" style="font-size: 0.8125em; font-weight: 700; letter-spacing: 0.01em; padding-left: 3em; padding-right: 3em;" href="#" title="">Shop Now!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="porto-grid-item grid-col-1-4 grid-col-md-1-2 grid-height-1-2" style="position: absolute; left: 50%; top: 0px;">
            <div class="porto-ibanner" style="background: #f4f4f4;">
                <img src="https://www.portotheme.com/magento2/porto/pub/media/wysiwyg/smartwave/porto/homepage/07/shop7_home_banner2.jpg">
                <div class="porto-ibanner-desc no-padding d-flex">
                    <div class="porto-ibanner-layer" style="left: 9%; top: 12%;">
                        <h3 style="font-size: 1.5em; line-height: 1; letter-spacing: 0;" class="vc_custom_heading mb-2 align-left">Porto Watches</h3>
                        <h4 style="font-size: 1.8125em; line-height: 1; font-weight: 800; letter-spacing: -0.04em;" class="vc_custom_heading mb-2 pb-1 text-sale align-left heading-secondary">
                            <sup>
                                <del><b>20%</b></del>
                            </sup>
                            30%<sup>OFF</sup>
                        </h4>
                        <div class="btn-container mb-0 d-inline-block"><a class="btn btn-modern btn-md btn-dark" style="font-weight: 700; padding: 0.875em 1.5em;" href="#" title="">Shop Now</a></div>
                    </div>
                    <div class="porto-ibanner-layer" style="background-image: url(https://www.portotheme.com/magento2/porto/pub/media/wysiwyg/smartwave/porto/homepage/07/shop7_brand1.png);background-position: center;background-repeat: no-repeat;background-size: contain;width: 3rem; height: 1rem; left: 9%; bottom: 10%;"></div>
                </div>
            </div>
        </div>
        <div class="porto-grid-item grid-col-1-4 grid-col-md-1-2 grid-height-1" style="position: absolute; left: 74.9573%; top: 0px;">
            <div class="porto-ibanner" style="background: #b0bac3;">
                <img src="https://www.portotheme.com/magento2/porto/pub/media/wysiwyg/smartwave/porto/homepage/07/shop7_home_banner4.jpg">
                <div class="porto-ibanner-desc no-padding d-flex">
                    <div class="porto-ibanner-layer" style="width: 70%; left: 50%; transform: translateX(-50%); bottom: 8.4%;">
                        <p style="font-size: 1.5em; line-height: 1; font-weight: 700; letter-spacing: 0.01em;" class="vc_custom_heading mb-2 pb-1 coupon-sale-text align-left heading-light">Leather Jackets</p>
                        <p style="font-size: 1em; line-height: 1; font-weight: 700; letter-spacing: 0.01em;" class="vc_custom_heading coupon-sale-text mb-3 align-left"><i>UP TO</i><b>$100</b> OFF</p>
                        <div class="btn-container text-center"><a class="btn btn-modern btn-lg btn-light d-block" style="font-size: 0.8125em;" href="#" title="">GET YOURS!</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="porto-grid-item grid-col-1-4 grid-col-md-1-2 grid-height-1-2" style="position: absolute; left: 50%; top: 260px;">
            <div class="porto-ibanner" style="border: 10px solid #65829d;">
                <img src="https://www.portotheme.com/magento2/porto/pub/media/wysiwyg/smartwave/porto/homepage/07/shop7_home_banner3.jpg">
                <div class="porto-ibanner-desc no-padding d-flex">
                    <div class="porto-ibanner-layer" style="width: 80%; left: 50%; top: 50%; transform: translate(-50%, -50%);">
                        <h3 style="font-size: 1.375rem; line-height: 1.35; text-align: center;" class="vc_custom_heading mb-0">DEAL PROMOS</h3>
                        <h4 style="font-size: 0.9375rem; color: #777777; line-height: 1; text-align: center; font-weight: 600;" class="vc_custom_heading mb-3 text-uppercase">STARTING AT $99</h4>
                        <div class="btn-container mb-0 text-center"><a class="btn btn-modern btn-md btn-dark" style="font-weight: 700; padding: 0.875em 1.5em;" href="#" title="">Shop Now</a></div>
                    </div>
                    <div class="porto-ibanner-layer" style="left: 7%; top: 8%;">
                        <h6 style="font-size: 1em;" class="vc_custom_heading sale-label mb-0 background-color-dark align-left heading-light">
                            50<small><sup>%</sup><sub>OFF</sub></small>
                        </h6>
                    </div>
                    <div class="porto-ibanner-layer" style="right: 7%; top: 8%;">
                        <h6 style="font-size: 0.75em;" class="vc_custom_heading sale-label mb-0 background-color-dark align-left heading-light">
                            70<small><sup>%</sup><sub>OFF</sub></small>
                        </h6>
                    </div>
                    <div class="porto-ibanner-layer" style="right: 9%; bottom: 11%;">
                        <h6 style="font-size: 0.625em;" class="vc_custom_heading sale-label mb-0 background-color-dark align-left heading-light">
                            30<small><sup>%</sup><sub>OFF</sub></small>
                        </h6>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid-col-sizer"></div>
    </div>
    <style scope="scope">
        .porto-banner-layout {opacity: 0;}
        .porto-ibanner-layer {
            position: absolute;
            z-index: 10;
        }
        .porto-preset-layout .porto-grid-item>*,
        .porto-preset-layout .porto-ibanner,
        .porto-preset-layout .porto-ibanner>img {
            height: 100%;
            margin-bottom: 0;
        }
        .porto-banner-layout .porto-grid-item {
            padding: 10px;
        }
        .porto-banner-layout {
            margin: -10px -10px 10px;
        }
        .porto-banner-layout .grid-col-1-2 {
            flex: 0 0 50%;
            width: 50%;
        }
        .porto-banner-layout .grid-col-1-4 {
            flex: 0 0 25%;
            width: 25%;
        }
        .porto-banner-layout .grid-col-sizer {
            flex: 0 0 25%;
            width: 25%;
        }
        .porto-banner-layout .grid-height-1 {
            height: 520px;
        }
        .porto-banner-layout .grid-height-1-2 {
            height: 260px;
        }
        @media (max-width: 767px) {
            .porto-banner-layout .grid-col-md-1 {
                flex: 0 0 100%;
                width: 100%;
            }
            .porto-banner-layout .grid-col-md-1-2 {
                flex: 0 0 50%;
                width: 50%;
            }
            .porto-banner-layout .grid-col-sizer {
                flex: 0 0 50%;
                width: 50%;
            }
            .porto-banner-layout .grid-height-1 {
                height: 347px;
            }
            .porto-banner-layout .grid-height-1-2 {
                height: 173px;
            }
        }
        @media (max-width: 480px) {
            .porto-banner-layout .porto-grid-item {
                flex: 0 0 100%;
                width: 100%;
            }
        }
    </style>
    <script type="text/javascript">
        require([
            'jquery',
            'packery'
        ], function ($, Packery) {
            $.bridget( 'packery', Packery );
            var $container = $('#banner-masonry-demo-7');
            $container.css('opacity', 0);
            if ($container.length > 0) {
                $container.imagesLoaded(function(){
                    $container.packery({
                        itemSelector: ".porto-grid-item",
                        columnWidth: ".grid-col-sizer",
                        percentPosition: true
                    });
                });
                setTimeout(function(){
                    $container.animate({
                        opacity: 1
                    }, 200);
                }, 500);
            }
        });
    </script>
</div>
