<?php



//$productsBlock = $this->getLayout()->createBlock(\Magento\CatalogWidget\Block\Product\ProductsList::class)->getConditions();
//$productsBlock->setTitle("My products");
//$productsBlock->setProductsCount(5);
//$productsBlock->setTemplate("product/widget/content/grid.phtml");
//$productsBlock->setConditions(
//    [
//        1 => [
//            'type' => \Magento\CatalogWidget\Model\Rule\Condition\Combine::class,
//            'aggregator' => 'all',
//            'value' => '1',
//            'new_child' => '',
//        ],
//        '1-1' => [
//            'type' => \Magento\CatalogWidget\Model\Rule\Condition\Product::class,
//            'attribute' => 'category_ids',
//            'operator' => '==',
//            'value' => '4',
//        ]
//    ]
//);
//echo $productsBlock->toHtml();
//echo $this->getLayout()->createBlock("\Magento\CatalogWidget\Block\Product\ProductsList")->setTitle("WidgetTitle")->setProductsCount(5)->setOption1("Data1")->setOption2("Data2")->setTemplate("product/widget/content/grid.phtml")->toHtml();

