<?php
$categories = $block->getCategoryCollection();
$title = $block->getTitle() ? __($block->getTitle()) : __('Categories');

?>
<?php if ($title):?>
    <div class="block-title">
        <strong><?php echo $block->escapeHtml($title) ?></strong>
    </div>
<?php endif ?>
<div class="block-content catalog-category homepage-categories-container">
    <?php foreach($categories as $category):?>
        <span class="category">
        	<a href="<?php echo $block->escapeUrl($category->getUrl()) ?>" class="homepage-category">
            		<?php if($category->getImage()):?>
                        <div><img src="<?php echo $category->getImage() ?>" alt="" ></div>
                        <div><span class="cat-title"><?php echo $block->escapeHtml($category->getName()) ?></span></div>
                    <?php else:?>
                        <div><img src="<?php echo $block->getViewFileUrl('/images/empty_image_category.jpg/')?>" alt="" ></div>
                        <div><span class="cat-title"><?php echo $block->escapeHtml($category->getName()) ?></span><div>
                    <?php endif;?>
        	</a>
        </span>
    <?php
    endforeach;
    ?>
</div>
